#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "images/pic1.h"
#include "images/pic2.h"
#include "images/pic3.h"
#include "images/pic4.h"
#include "images/pic5.h"
#include "images/win.h"
#include "images/lose.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"


/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAYBG,
  PLAY,
  WIN,
  WINBG,
  LOSE,
  LOSEBG,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;


  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case START:
        drawFullScreenImageDMA(pic1);
        char startInstruction[] = "Press Enter to Start the Game"; 
        waitForVBlank();
        drawString(110, 48, startInstruction, BLUE);

        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)){
          state = START;
        }
        while (state == START){
          if (KEY_DOWN(BUTTON_START, BUTTONS)){
            state = PLAYBG;
            previousButtons = BUTTONS;
          }
        }
        break;

      case PLAYBG:
          //drawFullScreenImageDMA(pic2);
          fillScreenDMA(WHITE);
          waitForVBlank();
          char score[] = "Score:";
          drawString(140, 60, score, RED);
          state = PLAY;
          break;

      case PLAY:
          waitForVBlank();
          Object o;
          o.row = 25;
          o.col = 25;
          drawImageDMA(o.row, o.col, 20, 20, pic3); 
          waitForVBlank();
          drawImageDMA(100, 120, 40, 40, pic5);
          waitForVBlank();
        while (state == PLAY){
          if (KEY_DOWN(BUTTON_SELECT, BUTTONS)){
            state = START;
            previousButtons = BUTTONS;
          }
          if (o.row <= 0 || o.row >= 140 || o.col <= 0){
              state = LOSEBG;
          }
          if (o. row >= 80 && o.col >= 100 && o. col <= 159){
              state = LOSEBG;
          }
          if (o.col >= 213){
              state = WINBG;
          }
          //drawRectDMA(140, 100, 20, 20, WHITE);
          //waitForVBlank();
          // meaning ful text:
          int score = o.col * 100 / 210;
          char buffer[4]; 
          snprintf(buffer, sizeof(buffer), "%d", score);
          drawString(140, 100, buffer, RED);
          waitForVBlank();

          if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)){
            drawRectDMA(o.row, o.col, 1, 20, WHITE);
            waitForVBlank();
            drawImageDMA(100, 120, 40, 40, pic5);
            waitForVBlank();
            o.col += 1;
            drawImageDMA(o.row, o.col, 20, 20, pic3); 
            waitForVBlank();
            drawRectDMA(140, 100, 20, 20, WHITE);
            waitForVBlank();
          }
          if (KEY_DOWN(BUTTON_LEFT, BUTTONS)){
            drawRectDMA(o.row, o.col + 19, 1, 20, WHITE);
            waitForVBlank();
            drawImageDMA(100, 120, 40, 40, pic5);
            waitForVBlank();
            o.col -= 1;
            drawImageDMA(o.row, o.col, 20, 20, pic3); 
            waitForVBlank();
            drawRectDMA(140, 100, 20, 20, WHITE);
            waitForVBlank();
          }
          if (KEY_DOWN(BUTTON_UP, BUTTONS)){
            drawRectDMA(o.row + 19, o.col, 20, 1, WHITE);
            waitForVBlank();
            drawImageDMA(100, 120, 40, 40, pic5);
            waitForVBlank();
            o.row -= 1;
            drawImageDMA(o.row, o.col, 20, 20, pic3); 
            waitForVBlank();
            //drawRectDMA(140, 100, 20, 20, WHITE);
            //waitForVBlank();
          }
          if (KEY_DOWN(BUTTON_DOWN, BUTTONS)){
            drawRectDMA(o.row, o.col, 20, 1, WHITE);
            waitForVBlank();
            drawImageDMA(100, 120, 40, 40, pic5);
            waitForVBlank();
            o.row += 1;
            drawImageDMA(o.row, o.col, 20, 20, pic3); 
            waitForVBlank();
            //drawRectDMA(140, 100, 20, 20, WHITE);
            //waitForVBlank();
          }
        }

        break;

      case WINBG:
        drawFullScreenImageDMA(pic2);
        waitForVBlank();
        state = WIN;
      break;

      case WIN:
        waitForVBlank();
        char w[] = "You win(Press backspace to replay)";
        waitForVBlank();
        drawString(110, 20, w, GREEN);

        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)){
          state = START;
        }
      break;

      case LOSEBG:
        drawFullScreenImageDMA(lose);
        waitForVBlank();
        state = LOSE;
        break;

      case LOSE:
        waitForVBlank();
        char l[] = "You Lost(Press backspace to retry)";
        waitForVBlank();
        drawString(110, 20, l, RED);

        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)){
          state = START;
        }
      break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }
  UNUSED(previousButtons); // You can remove this once previousButtons is used
  return 0;
}

